version: '3'
services:
  frontend:
    image: react-app
    ports:
      - '3000:3000'
    depends_on:
      - backend
    networks:
      - ploadnplay-net

  backend:
    image: api-server
    depends_on:
      - mongodb
    networks:
      - ploadnplay-net

  mongodb:
    image: mongo
    networks:
      - ploadnplay-net
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

networks:
  ploadnplay-net:
    driver: bridge


volumes:
  mongo-data:
    driver: local